"""Initial migration

Revision ID: 0256d1184817
Revises: 05f40d0a0359
Create Date: 2024-01-13 18:19:07.604139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0256d1184817'
down_revision = '05f40d0a0359'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'created_at')
    # ### end Alembic commands ###
